modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/seymourimadeit/illagersweararmor/issues" #optional
license="GPLv3"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="zillagersweararmor" #mandatory
version="1.1.1" #mandatory
displayName="Illagers Wear Armor" #mandatory
updateJSONURL="https://raw.githubusercontent.com/seymourimadeit/illagersweararmor/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor" #optional
credits="TallestEgg" #optional
authors="TallestEgg" #optional
description='''
Illagers with armor.
'''
[[dependencies.illagersweararmor]] 
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.illagersweararmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.illagersweararmor]] 
    modId="enchantwithmob" #mandatory
    mandatory=false #mandatory
    versionRange="[1.18.1-3.0.0,)" #mandatory
    ordering="AFTER"
    side="BOTH"
[[dependencies.illagersweararmor]] 
    modId="hunterillager"
    mandatory=false #mandatory
    versionRange="[1.18.1-3.0.0,)"
    ordering="AFTER"
    side="BOTH"